/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_shakehand.c
  Source: app_shakehand.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "app_shakehand.h"

static const uint32_t byd_interfaces_msg_app_shakehand_ops [] =
{
  /* app_shakehand */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_shakehand, ShakehandStatus),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_shakehand, APA_LSMSubMTReq_enum),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_shakehand, APA_LSMSubMTLevel_enum),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_app_shakehand_desc =
{
  .m_size = sizeof (byd_interfaces_msg_app_shakehand),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::app_shakehand_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_app_shakehand_ops,
  .m_meta = ""
};

