/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: fusion_parkingtarget.c
  Source: fusion_parkingtarget.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "fusion_parkingtarget.h"

static const uint32_t byd_interfaces_msg_fusion_parkingtarget_ops [] =
{
  /* fusion_parkingtarget */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_fusion_parkingtarget, TimeStampMs),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_fusion_parkingtarget, position), (3u << 16u) + 23u /* Position */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_fusion_parkingtarget, ParkingSpace), (3u << 16u) + 27u /* ParkingSpace */,
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_fusion_parkingtarget, Theta),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_fusion_parkingtarget, TraceParkingID_Cam),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_fusion_parkingtarget, TraceParkingID_USS),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_fusion_parkingtarget, ParkInMode),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_fusion_parkingtarget, distance_01),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_fusion_parkingtarget, distance_23),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_fusion_parkingtarget, distance_03),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_fusion_parkingtarget, depth_block),
  DDS_OP_RTS,

  /* Position */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Heading),
  DDS_OP_RTS,

  /* ParkingSpace */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpace, id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpace, Width),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpace, ParkingSpaceValid),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpace, ParkingSpaceType),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_fusion_parkingtarget_desc =
{
  .m_size = sizeof (byd_interfaces_msg_fusion_parkingtarget),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::fusion_parkingtarget_",
  .m_keys = NULL,
  .m_nops = 29,
  .m_ops = byd_interfaces_msg_fusion_parkingtarget_ops,
  .m_meta = ""
};

