
#ifndef __byd_interfaces__msg__hmi__srv__ai__idl__
#define  __byd_interfaces__msg__hmi__srv__ai__idl__

module byd_interfaces {
  module msg {
    struct hmi_srv_ai {
     uint64 timestampUs;
     int32 width;
      int32 height;
      int32 size;
     uint8 data[614400];
    };
  };
};
#endif
