/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Parkingspace.c
  Source: Parkingspace.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Parkingspace.h"

static const uint32_t uss_msgs_msg_ParkingSpace_ops [] =
{
  /* ParkingSpace */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpace, id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ParkingSpace, Width),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpace, ParkingSpaceValid),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpace, ParkingSpaceType),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_ParkingSpace_desc =
{
  .m_size = sizeof (uss_msgs_msg_ParkingSpace),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::ParkingSpace_",
  .m_keys = NULL,
  .m_nops = 13,
  .m_ops = uss_msgs_msg_ParkingSpace_ops,
  .m_meta = ""
};

