/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Parking_next_step.c
  Source: Parking_next_step.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Parking_next_step.h"

static const uint32_t uss_msgs_msg_Parking_next_nextstep_ops [] =
{
  /* Parking_next_nextstep */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P3_Y),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_Parking_next_nextstep_desc =
{
  .m_size = sizeof (uss_msgs_msg_Parking_next_nextstep),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::Parking_next_nextstep_",
  .m_keys = NULL,
  .m_nops = 9,
  .m_ops = uss_msgs_msg_Parking_next_nextstep_ops,
  .m_meta = ""
};

