#ifndef __byd_interfaces__msg__Position__idl__
#define __byd_interfaces__msg__Position__idl__

module uss_msgs {
  module msg {
    struct Position {
      double X;
	    double Y;
    	double Heading;
};
  };
};
#endif
