#ifndef __byd_interfaces__msg__Freespacecell__idl__
#define __byd_interfaces__msg__Freespacecell__idl__

module uss_msgs {
  module msg {
    struct FreeSpaceCell {
   uint8 Status;
	 uint16 Probability;
};
  };
};
#endif
