/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Uss.c
  Source: Uss.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Uss.h"

static const uint32_t byd_interface_msg_Uss_ops [] =
{
  /* Uss */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interface_msg_Uss, channel),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interface_msg_Uss, SendID),
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interface_msg_Uss, timestamp),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (byd_interface_msg_Uss, status),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interface_msg_Uss, num),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY, offsetof (byd_interface_msg_Uss, ts), 16u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interface_msg_Uss_desc =
{
  .m_size = sizeof (byd_interface_msg_Uss),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interface::msg::dds_::Uss_",
  .m_keys = NULL,
  .m_nops = 7,
  .m_ops = byd_interface_msg_Uss_ops,
  .m_meta = ""
};

