#ifndef __byd_interfaces__msg__vehiclecontrol__app__displayinfo__idl__
#define __byd_interfaces__msg__vehiclecontrol__app__displayinfo__idl__

module byd_interfaces {
  module msg {
    struct vehiclecontrol_app_displayinfo{
    double Display_X;  
	  double Display_Y;  
	  double Display_Yaw;  
    };
  };
};
#endif
