/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: vehiclecontrol_app_displayinfo.c
  Source: vehiclecontrol_app_displayinfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "vehiclecontrol_app_displayinfo.h"

static const uint32_t byd_interfaces_msg_vehiclecontrol_app_displayinfo_ops [] =
{
  /* vehiclecontrol_app_displayinfo */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_vehiclecontrol_app_displayinfo, Display_X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_vehiclecontrol_app_displayinfo, Display_Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_vehiclecontrol_app_displayinfo, Display_Yaw),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_vehiclecontrol_app_displayinfo_desc =
{
  .m_size = sizeof (byd_interfaces_msg_vehiclecontrol_app_displayinfo),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::vehiclecontrol_app_displayinfo_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_vehiclecontrol_app_displayinfo_ops,
  .m_meta = ""
};

