/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: fusion_parkingtarget.h
  Source: fusion_parkingtarget.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_FUSION_PARKINGTARGET_H
#define DDSC_FUSION_PARKINGTARGET_H

#include "Parkingspace.h"

#include "Position.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_fusion_parkingtarget
{
  int64_t TimeStampMs;
  struct uss_msgs_msg_Position position;
  struct uss_msgs_msg_ParkingSpace ParkingSpace;
  double Theta;
  uint8_t TraceParkingID_Cam;
  uint8_t TraceParkingID_USS;
  uint8_t ParkInMode;
  double distance_01;
  double distance_23;
  double distance_03;
  double depth_block;
} byd_interfaces_msg_fusion_parkingtarget;

extern const dds_topic_descriptor_t byd_interfaces_msg_fusion_parkingtarget_desc;

#define byd_interfaces_msg_fusion_parkingtarget__alloc() \
((byd_interfaces_msg_fusion_parkingtarget*) dds_alloc (sizeof (byd_interfaces_msg_fusion_parkingtarget)));

#define byd_interfaces_msg_fusion_parkingtarget_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_fusion_parkingtarget_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_FUSION_PARKINGTARGET_H */
