/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: ObstacleInfo2.h
  Source: ObstacleInfo2.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_OBSTACLEINFO2_H
#define DDSC_OBSTACLEINFO2_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct uss_msgs_msg_ObstacleInfo2
{
  uint8_t ObstacleType;
  int32_t Obstacle_X;
  int32_t Obstacle_Y;
} uss_msgs_msg_ObstacleInfo2;

extern const dds_topic_descriptor_t uss_msgs_msg_ObstacleInfo2_desc;

#define uss_msgs_msg_ObstacleInfo2__alloc() \
((uss_msgs_msg_ObstacleInfo2*) dds_alloc (sizeof (uss_msgs_msg_ObstacleInfo2)));

#define uss_msgs_msg_ObstacleInfo2_free(d,o) \
dds_sample_free ((d), &uss_msgs_msg_ObstacleInfo2_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_OBSTACLEINFO2_H */
