/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: TopMachine.h
  Source: TopMachine.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_TOPMACHINE_H
#define DDSC_TOPMACHINE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_topM
{
  uint8_t top_proce_sts;
  uint8_t padding[7];
} byd_interfaces_msg_topM;

extern const dds_topic_descriptor_t byd_interfaces_msg_topM_desc;

#define byd_interfaces_msg_topM__alloc() \
((byd_interfaces_msg_topM*) dds_alloc (sizeof (byd_interfaces_msg_topM)));

#define byd_interfaces_msg_topM_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_topM_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_TOPMACHINE_H */
