/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: apa_nav.h
  Source: apa_nav.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_APA_NAV_H
#define DDSC_APA_NAV_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_apa_nav
{
  int64_t TimeStampMs;
  double nav_pos_x;
  double nav_pos_y;
  double nav_heading;
  uint8_t nav_status;
} byd_interfaces_msg_apa_nav;

extern const dds_topic_descriptor_t byd_interfaces_msg_apa_nav_desc;

#define byd_interfaces_msg_apa_nav__alloc() \
((byd_interfaces_msg_apa_nav*) dds_alloc (sizeof (byd_interfaces_msg_apa_nav)));

#define byd_interfaces_msg_apa_nav_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_apa_nav_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_APA_NAV_H */
