/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_park_type.h
  Source: app_park_type.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_APP_PARK_TYPE_H
#define DDSC_APP_PARK_TYPE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_app_park_type
{
  uint8_t APA_Park_Function;
} byd_interfaces_msg_app_park_type;

extern const dds_topic_descriptor_t byd_interfaces_msg_app_park_type_desc;

#define byd_interfaces_msg_app_park_type__alloc() \
((byd_interfaces_msg_app_park_type*) dds_alloc (sizeof (byd_interfaces_msg_app_park_type)));

#define byd_interfaces_msg_app_park_type_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_app_park_type_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_APP_PARK_TYPE_H */
