/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_nav_cmd.h
  Source: app_nav_cmd.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_APP_NAV_CMD_H
#define DDSC_APP_NAV_CMD_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_app_nav_cmd
{
  uint8_t APA_nav_cmd;
} byd_interfaces_msg_app_nav_cmd;

extern const dds_topic_descriptor_t byd_interfaces_msg_app_nav_cmd_desc;

#define byd_interfaces_msg_app_nav_cmd__alloc() \
((byd_interfaces_msg_app_nav_cmd*) dds_alloc (sizeof (byd_interfaces_msg_app_nav_cmd)));

#define byd_interfaces_msg_app_nav_cmd_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_app_nav_cmd_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_APP_NAV_CMD_H */
