/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_status.h
  Source: app_status.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_APP_STATUS_H
#define DDSC_APP_STATUS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_app_status
{
  uint8_t APAStatus;
} byd_interfaces_msg_app_status;

extern const dds_topic_descriptor_t byd_interfaces_msg_app_status_desc;

#define byd_interfaces_msg_app_status__alloc() \
((byd_interfaces_msg_app_status*) dds_alloc (sizeof (byd_interfaces_msg_app_status)));

#define byd_interfaces_msg_app_status_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_app_status_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_APP_STATUS_H */
