/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_mode.h
  Source: app_mode.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_APP_MODE_H
#define DDSC_APP_MODE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_app_mode
{
  uint8_t ParkInMode;
} byd_interfaces_msg_app_mode;

extern const dds_topic_descriptor_t byd_interfaces_msg_app_mode_desc;

#define byd_interfaces_msg_app_mode__alloc() \
((byd_interfaces_msg_app_mode*) dds_alloc (sizeof (byd_interfaces_msg_app_mode)));

#define byd_interfaces_msg_app_mode_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_app_mode_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_APP_MODE_H */
