/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Coordinate.h
  Source: Coordinate.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_COORDINATE_H
#define DDSC_COORDINATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct uss_msgs_msg_Coordinate
{
  double X;
  double Y;
  double Yaw;
  uint8_t rajectoryDirection;
  double Curvature;
} uss_msgs_msg_Coordinate;

extern const dds_topic_descriptor_t uss_msgs_msg_Coordinate_desc;

#define uss_msgs_msg_Coordinate__alloc() \
((uss_msgs_msg_Coordinate*) dds_alloc (sizeof (uss_msgs_msg_Coordinate)));

#define uss_msgs_msg_Coordinate_free(d,o) \
dds_sample_free ((d), &uss_msgs_msg_Coordinate_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_COORDINATE_H */
