/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Freespacefusion.h
  Source: Freespacefusion.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_FREESPACEFUSION_H
#define DDSC_FREESPACEFUSION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct uss_msgs_msg_FreeSpacefusion
{
  uint8_t Status;
} uss_msgs_msg_FreeSpacefusion;

extern const dds_topic_descriptor_t uss_msgs_msg_FreeSpacefusion_desc;

#define uss_msgs_msg_FreeSpacefusion__alloc() \
((uss_msgs_msg_FreeSpacefusion*) dds_alloc (sizeof (uss_msgs_msg_FreeSpacefusion)));

#define uss_msgs_msg_FreeSpacefusion_free(d,o) \
dds_sample_free ((d), &uss_msgs_msg_FreeSpacefusion_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_FREESPACEFUSION_H */
