/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Parkingspaceinfo.h
  Source: Parkingspaceinfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_PARKINGSPACEINFO_H
#define DDSC_PARKINGSPACEINFO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct uss_msgs_msg_ParkingSpaceInfo
{
  uint8_t id;
  int32_t P0_X;
  int32_t P0_Y;
  int32_t P1_X;
  int32_t P1_Y;
  int32_t P2_X;
  int32_t P2_Y;
  int32_t P3_X;
  int32_t P3_Y;
  int32_t P0_X_Offset;
  int32_t P0_Y_Offset;
  int32_t P1_X_Offset;
  int32_t P1_Y_Offset;
  int32_t P2_X_Offset;
  int32_t P2_Y_Offset;
  int32_t P3_X_Offset;
  int32_t P3_Y_Offset;
  int32_t Width;
  uint8_t ParkingSpaceValid;
  uint8_t ParkingSpaceType;
} uss_msgs_msg_ParkingSpaceInfo;

extern const dds_topic_descriptor_t uss_msgs_msg_ParkingSpaceInfo_desc;

#define uss_msgs_msg_ParkingSpaceInfo__alloc() \
((uss_msgs_msg_ParkingSpaceInfo*) dds_alloc (sizeof (uss_msgs_msg_ParkingSpaceInfo)));

#define uss_msgs_msg_ParkingSpaceInfo_free(d,o) \
dds_sample_free ((d), &uss_msgs_msg_ParkingSpaceInfo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_PARKINGSPACEINFO_H */
