/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_nav_cmd.c
  Source: app_nav_cmd.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "app_nav_cmd.h"

static const uint32_t byd_interfaces_msg_app_nav_cmd_ops [] =
{
  /* app_nav_cmd */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_nav_cmd, APA_nav_cmd),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_app_nav_cmd_desc =
{
  .m_size = sizeof (byd_interfaces_msg_app_nav_cmd),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::app_nav_cmd_",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = byd_interfaces_msg_app_nav_cmd_ops,
  .m_meta = ""
};

