#ifndef __byd_interfaces__msg__geometry__statusinfo__ctrl__idl__
#define  __byd_interfaces__msg__geometry__statusinfo__ctrl__idl__

module byd_interfaces {
  module msg {
    struct geometry_statusinfo_ctrl {
    long long TimeStampMs;
     uint8 PlanningStatus;

   };
  };
};
#endif
