/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: hmi_srv_ai.c
  Source: hmi_srv_ai.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "hmi_srv_ai.h"

static const uint32_t byd_interfaces_msg_hmi_srv_ai_ops [] =
{
  /* hmi_srv_ai */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_hmi_srv_ai, timestampUs),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_hmi_srv_ai, width),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_hmi_srv_ai, height),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_hmi_srv_ai, size),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_hmi_srv_ai, data), 614400u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_hmi_srv_ai_desc =
{
  .m_size = sizeof (byd_interfaces_msg_hmi_srv_ai),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::hmi_srv_ai_",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = byd_interfaces_msg_hmi_srv_ai_ops,
  .m_meta = ""
};

