/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: uss_dis_to_ui.c
  Source: uss_dis_to_ui.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "uss_dis_to_ui.h"

static const uint32_t byd_interfaces_msg_uss_dis_ui_ops [] =
{
  /* uss_dis_ui */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_uss_dis_ui, Uss_ui), (3u << 16u) + 4u /* Uss_UI */,
  DDS_OP_RTS,

  /* Uss_UI */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (uss_msgs_msg_Uss_UI, timestamp),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Uss_UI, distance_app), 12u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_uss_dis_ui_desc =
{
  .m_size = sizeof (byd_interfaces_msg_uss_dis_ui),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::uss_dis_ui_",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = byd_interfaces_msg_uss_dis_ui_ops,
  .m_meta = ""
};

