/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: cam_sensing.c
  Source: cam_sensing.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "cam_sensing.h"

static const uint32_t byd_interfaces_msg_cam_sensing_ops [] =
{
  /* cam_sensing */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_cam_sensing, TimeStampMs),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_cam_sensing, position), (3u << 16u) + 19u /* Position */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (byd_interfaces_msg_cam_sensing, parkingSpaceInfo), 25u, (5u << 16u) + 23u /* ParkingSpaceInfo */, sizeof (uss_msgs_msg_ParkingSpaceInfo),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (byd_interfaces_msg_cam_sensing, freeSpaceCell), 62500u, (5u << 16u) + 59u /* FreeSpaceCell */, sizeof (uss_msgs_msg_FreeSpaceCell),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (byd_interfaces_msg_cam_sensing, ObstacleInfo), 25u, (5u << 16u) + 59u /* ObstacleInfo */, sizeof (uss_msgs_msg_ObstacleInfo),
  DDS_OP_RTS,

  /* Position */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Heading),
  DDS_OP_RTS,

  /* ParkingSpaceInfo */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P0_X_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P0_Y_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P1_X_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P1_Y_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P2_X_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P2_Y_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P3_X_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, P3_Y_Offset),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, Width),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, ParkingSpaceValid),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpaceInfo, ParkingSpaceType),
  DDS_OP_RTS,

  /* FreeSpaceCell */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_FreeSpaceCell, Status),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (uss_msgs_msg_FreeSpaceCell, Probability),
  DDS_OP_RTS,

  /* ObstacleInfo */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ObstacleInfo, ObstacleType),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ObstacleInfo, Obstacle_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ObstacleInfo, Obstacle_Y),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ObstacleInfo, VehicleDirection),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_cam_sensing_desc =
{
  .m_size = sizeof (byd_interfaces_msg_cam_sensing),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::cam_sensing_",
  .m_keys = NULL,
  .m_nops = 39,
  .m_ops = byd_interfaces_msg_cam_sensing_ops,
  .m_meta = ""
};

