#ifndef __byd_interfaces__msg__Data__uss__idl__
#define __byd_interfaces__msg__Data__uss__idl__

module uss_msgs {
  module msg {
    struct Data_Uss {
     long long timestamp;
	int32 Distance;
	uint32 Time_RTEND;  ///> us     //20220602新增
	uint32 Time0;  ///> us
	uint32 Time1;  ///> us
	uint32 Time2;  ///> us
	uint32 Time3;  ///> us
	uint32 Time4;  ///> us
	uint32 Time5;  ///> us
	uint32 Time6;  ///> us    //20220602新增
	uint32 Time7;  ///> us    //20220602新增
    uint32 Time8;  ///> us   
	uint32 Time9;  ///> us    
	uint16 Echo_Height_Info;   //20220606新增
    uint8 SendID;

};
  };
};
#endif
