/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Data_uss.c
  Source: Data_uss.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Data_uss.h"

static const uint32_t uss_msgs_msg_Data_Uss_ops [] =
{
  /* Data_Uss */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Data_Uss, timestamp),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Data_Uss, Distance),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time_RTEND),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time0),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time1),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time2),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time3),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time4),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time5),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time6),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time7),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time8),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_Data_Uss, Time9),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (uss_msgs_msg_Data_Uss, Echo_Height_Info),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_Data_Uss, SendID),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_Data_Uss_desc =
{
  .m_size = sizeof (uss_msgs_msg_Data_Uss),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::Data_Uss_",
  .m_keys = NULL,
  .m_nops = 16,
  .m_ops = uss_msgs_msg_Data_Uss_ops,
  .m_meta = ""
};

