#include "nav_msgs/msg/Position.idl"
#include "nav_msgs/msg/Freespacefusion.idl"


#ifndef __byd_interfaces__msg__fusion__gridmap__idl__
#define __byd_interfaces__msg__fusion__gridmap__idl__

module byd_interfaces {
  module msg {
    struct fusion_gridmap {
      long long TimeStampMs;
      uss_msgs::msg::Position position;
        uss_msgs::msg::FreeSpacefusion freeSpacefusion[62500];

    };
  };
};
#endif
