

#ifndef __byd_interfaces__msg__geometry__completeinfo__ctrl__idl__
#define  __byd_interfaces__msg__geometry__completeinfo__ctrl__idl__

module byd_interfaces {
  module msg {
    struct geometry_completeinfo_ctrl {
    long long TimeStampMs;
    uint8 IsPlanningCompleted;
   };
  };
};
#endif
