/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Imageparkingspaceinfo.c
  Source: Imageparkingspaceinfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Imageparkingspaceinfo.h"

static const uint32_t apa_msgs_msg_ImageParkingSpaceInfo_ops [] =
{
  /* ImageParkingSpaceInfo */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_ImageParkingSpaceInfo, ParkingSpaceType),
  DDS_OP_RTS
};

const dds_topic_descriptor_t apa_msgs_msg_ImageParkingSpaceInfo_desc =
{
  .m_size = sizeof (apa_msgs_msg_ImageParkingSpaceInfo),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "apa_msgs::msg::dds_::ImageParkingSpaceInfo_",
  .m_keys = NULL,
  .m_nops = 10,
  .m_ops = apa_msgs_msg_ImageParkingSpaceInfo_ops,
  .m_meta = ""
};

