/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Position.c
  Source: Position.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Position.h"

static const uint32_t uss_msgs_msg_Position_ops [] =
{
  /* Position */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Heading),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_Position_desc =
{
  .m_size = sizeof (uss_msgs_msg_Position),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::Position_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = uss_msgs_msg_Position_ops,
  .m_meta = ""
};

