#include "nav_msgs/msg/Position.idl"
#include "nav_msgs/msg/Freespacecell.idl"

#ifndef __byd_interfaces__msg__uss__map__idl__
#define   __byd_interfaces__msg__uss__map__idl__

module byd_interfaces {
  module msg {
    struct uss_map {
      long long TimeStampMs;
      uss_msgs::msg::Position position;
     uss_msgs::msg:: FreeSpaceCell freeSpaceCell[62500];
    };
  };
};
#endif
