/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: uss_obs_avoid.c
  Source: uss_obs_avoid.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "uss_obs_avoid.h"

static const uint32_t byd_interfaces_msg_uss_obs_ops [] =
{
  /* uss_obs */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_uss_obs, TimeStampMs),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_uss_obs, uss_obs_avoid), (3u << 16u) + 4u /* Uss_obs_avoid */,
  DDS_OP_RTS,

  /* Uss_obs_avoid */
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (uss_msgs_msg_Uss_obs_avoid, ussInfo_app), 12u, (5u << 16u) + 6u /* UssInfo_app */, sizeof (uss_msgs_msg_UssInfo_app),
  DDS_OP_RTS,

  /* UssInfo_app */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (uss_msgs_msg_UssInfo_app, timestamp),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_UssInfo_app, distance_app),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_UssInfo_app, theta_app),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_uss_obs_desc =
{
  .m_size = sizeof (byd_interfaces_msg_uss_obs),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::uss_obs_",
  .m_keys = NULL,
  .m_nops = 9,
  .m_ops = byd_interfaces_msg_uss_obs_ops,
  .m_meta = ""
};

