#ifndef __byd_interfaces__msg__Uss__ui__idl__
#define __byd_interfaces__msg__Uss__ui__idl__

module uss_msgs {
  module msg {
    struct Uss_UI {
      uint64 timestamp;
	    double distance_app[12];
};
  };
};
#endif
