/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Uss_obs.c
  Source: Uss_obs.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Uss_obs.h"

static const uint32_t uss_msgs_msg_Uss_obs_avoid_ops [] =
{
  /* Uss_obs_avoid */
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (uss_msgs_msg_Uss_obs_avoid, ussInfo_app), 12u, (5u << 16u) + 6u /* UssInfo_app */, sizeof (uss_msgs_msg_UssInfo_app),
  DDS_OP_RTS,

  /* UssInfo_app */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (uss_msgs_msg_UssInfo_app, timestamp),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_UssInfo_app, distance_app),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_UssInfo_app, theta_app),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_Uss_obs_avoid_desc =
{
  .m_size = sizeof (uss_msgs_msg_Uss_obs_avoid),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::Uss_obs_avoid_",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = uss_msgs_msg_Uss_obs_avoid_ops,
  .m_meta = ""
};

