#ifndef __byd_interfaces__msg__vehiclecontrol__app__parkinginfo__idl__
#define __byd_interfaces__msg__vehiclecontrol__app__parkinginfo__idl__

module byd_interfaces {
  module msg {
    struct vehiclecontrol_app_parkinginfo{
      uint8 Completed_App;
      uint8 ObstacleOnPath;
      uint8 PlanOvertime;
    };
  };
};
#endif
