#ifndef __byd_interfaces__msg__Imageparkingspaceinfo__idl__
#define __byd_interfaces__msg__Imageparkingspaceinfo__idl__

module apa_msgs {
  module msg {
    struct ImageParkingSpaceInfo {
    int32 P0_X;  //->Pixel
	int32 P0_Y;  //->Pixel
	int32 P1_X;  //->Pixel
	int32 P1_Y;  //->Pixel
	int32 P2_X;  //->Pixel
	int32 P2_Y;  //->Pixel
	int32 P3_X;  //->Pixel
	int32 P3_Y;  //->Pixel
	uint8 ParkingSpaceType;
};
  };
};
#endif
