/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Parkingtodisplay.c
  Source: Parkingtodisplay.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Parkingtodisplay.h"

static const uint32_t apa_msgs_msg_ParkingToDispaly_ops [] =
{
  /* ParkingToDispaly */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_ParkingToDispaly, Num),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_ParkingToDispaly, Width),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_ParkingToDispaly, ParkingSpaceValid),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_ParkingToDispaly, ParkingSpaceAvailable),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_ParkingToDispaly, ParkingSpaceType),
  DDS_OP_RTS
};

const dds_topic_descriptor_t apa_msgs_msg_ParkingToDispaly_desc =
{
  .m_size = sizeof (apa_msgs_msg_ParkingToDispaly),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "apa_msgs::msg::dds_::ParkingToDispaly_",
  .m_keys = NULL,
  .m_nops = 14,
  .m_ops = apa_msgs_msg_ParkingToDispaly_ops,
  .m_meta = ""
};

