#ifndef __byd_interfaces__msg__plan__statusinfo_ctrl__idl__
#define  __byd_interfaces__msg__plan__statusinfo_ctrl__idl__

module byd_interfaces {
  module msg {
    struct plan_statusinfo_ctrl {
    long long TimeStampMs;
     uint8 PlanningStatus;

   };
  };
};
#endif
