#ifndef __byd_interfaces__msg__vehiclecontrol__planj__reqinfo__idl__
#define __byd_interfaces__msg__vehiclecontrol__planj__reqinfo__idl__

module byd_interfaces {
  module msg {
    struct vehiclecontrol_planj_reqinfo{
      uint8 PlanningRequest;
      uint32 ObsUssInfo;
    };
  };
};
#endif
