/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Duration.h
  Source: Duration.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_DURATION_H
#define DDSC_DURATION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct builtin_interfaces_msg_Duration
{
  int32_t sec;
  uint32_t nanosec;
} builtin_interfaces_msg_Duration;

extern const dds_topic_descriptor_t builtin_interfaces_msg_Duration_desc;

#define builtin_interfaces_msg_Duration__alloc() \
((builtin_interfaces_msg_Duration*) dds_alloc (sizeof (builtin_interfaces_msg_Duration)));

#define builtin_interfaces_msg_Duration_free(d,o) \
dds_sample_free ((d), &builtin_interfaces_msg_Duration_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DURATION_H */
