/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Header.c
  Source: Header.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Header.h"

static const uint32_t std_msgs_msg_Header_ops [] =
{
  /* Header */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (std_msgs_msg_Header, stamp), (3u << 16u) + 6u /* Time */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (std_msgs_msg_Header, frame_id),
  DDS_OP_RTS,

  /* Time */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (builtin_interfaces_msg_Time, sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (builtin_interfaces_msg_Time, nanosec),
  DDS_OP_RTS
};

const dds_topic_descriptor_t std_msgs_msg_Header_desc =
{
  .m_size = sizeof (std_msgs_msg_Header),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 0u,
  .m_typename = "std_msgs::msg::dds_::Header_",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = std_msgs_msg_Header_ops,
  .m_meta = ""
};

