/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: CurrentInfo.h
  Source: CurrentInfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_CURRENTINFO_H
#define DDSC_CURRENTINFO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_CurrentInfo
{
  uint8_t ID;
  int32_t P0_X;
  int32_t P0_Y;
  int32_t P1_X;
  int32_t P1_Y;
  int32_t P2_X;
  int32_t P2_Y;
  int32_t P3_X;
  int32_t P3_Y;
  int32_t Width;
  double Angle;
  uint8_t ParkingSpaceAvailable;
  uint8_t ParkingSpaceType;
} byd_interfaces_msg_CurrentInfo;

extern const dds_topic_descriptor_t byd_interfaces_msg_CurrentInfo_desc;

#define byd_interfaces_msg_CurrentInfo__alloc() \
((byd_interfaces_msg_CurrentInfo*) dds_alloc (sizeof (byd_interfaces_msg_CurrentInfo)));

#define byd_interfaces_msg_CurrentInfo_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_CurrentInfo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_CURRENTINFO_H */
