/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: ObstacleInfo2.c
  Source: ObstacleInfo2.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "ObstacleInfo2.h"

static const uint32_t uss_msgs_msg_ObstacleInfo2_ops [] =
{
  /* ObstacleInfo2 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ObstacleInfo2, ObstacleType),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ObstacleInfo2, Obstacle_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ObstacleInfo2, Obstacle_Y),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_ObstacleInfo2_desc =
{
  .m_size = sizeof (uss_msgs_msg_ObstacleInfo2),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::ObstacleInfo2_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = uss_msgs_msg_ObstacleInfo2_ops,
  .m_meta = ""
};

