/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Parkingspace.h
  Source: Parkingspace.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_PARKINGSPACE_H
#define DDSC_PARKINGSPACE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct uss_msgs_msg_ParkingSpace
{
  uint8_t id;
  int32_t P0_X;
  int32_t P0_Y;
  int32_t P1_X;
  int32_t P1_Y;
  int32_t P2_X;
  int32_t P2_Y;
  int32_t P3_X;
  int32_t P3_Y;
  int32_t Width;
  uint8_t ParkingSpaceValid;
  uint8_t ParkingSpaceType;
} uss_msgs_msg_ParkingSpace;

extern const dds_topic_descriptor_t uss_msgs_msg_ParkingSpace_desc;

#define uss_msgs_msg_ParkingSpace__alloc() \
((uss_msgs_msg_ParkingSpace*) dds_alloc (sizeof (uss_msgs_msg_ParkingSpace)));

#define uss_msgs_msg_ParkingSpace_free(d,o) \
dds_sample_free ((d), &uss_msgs_msg_ParkingSpace_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_PARKINGSPACE_H */
