/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Position.h
  Source: Position.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_POSITION_H
#define DDSC_POSITION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct uss_msgs_msg_Position
{
  double X;
  double Y;
  double Heading;
} uss_msgs_msg_Position;

extern const dds_topic_descriptor_t uss_msgs_msg_Position_desc;

#define uss_msgs_msg_Position__alloc() \
((uss_msgs_msg_Position*) dds_alloc (sizeof (uss_msgs_msg_Position)));

#define uss_msgs_msg_Position_free(d,o) \
dds_sample_free ((d), &uss_msgs_msg_Position_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_POSITION_H */
