/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: vehiclecontrol_planj_reqinfo.h
  Source: vehiclecontrol_planj_reqinfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_VEHICLECONTROL_PLANJ_REQINFO_H
#define DDSC_VEHICLECONTROL_PLANJ_REQINFO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_vehiclecontrol_planj_reqinfo
{
  uint8_t PlanningRequest;
  uint32_t ObsUssInfo;
} byd_interfaces_msg_vehiclecontrol_planj_reqinfo;

extern const dds_topic_descriptor_t byd_interfaces_msg_vehiclecontrol_planj_reqinfo_desc;

#define byd_interfaces_msg_vehiclecontrol_planj_reqinfo__alloc() \
((byd_interfaces_msg_vehiclecontrol_planj_reqinfo*) dds_alloc (sizeof (byd_interfaces_msg_vehiclecontrol_planj_reqinfo)));

#define byd_interfaces_msg_vehiclecontrol_planj_reqinfo_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_vehiclecontrol_planj_reqinfo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_VEHICLECONTROL_PLANJ_REQINFO_H */
