/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: vehiclecontrol_planj_interfaceinfo.h
  Source: vehiclecontrol_planj_interfaceinfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#ifndef DDSC_VEHICLECONTROL_PLANJ_INTERFACEINFO_H
#define DDSC_VEHICLECONTROL_PLANJ_INTERFACEINFO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo
{
  uint8_t PlanningRequestCount;
} byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo;

extern const dds_topic_descriptor_t byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo_desc;

#define byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo__alloc() \
((byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo*) dds_alloc (sizeof (byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo)));

#define byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo_free(d,o) \
dds_sample_free ((d), &byd_interfaces_msg_vehiclecontrol_planj_interfaceinfo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_VEHICLECONTROL_PLANJ_INTERFACEINFO_H */
