/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: HelloWorldData.idl
  Source: HelloWorldData.cpp
  Cyclone DDS: v0.9.1

*****************************************************************/
#include "HelloWorldData.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
entity_properties_t get_type_props<::HelloWorldData::Msg>() {
  static std::mutex mtx;
  static entity_properties_t props;
  static std::atomic_bool initialized {false};

  if (initialized.load(std::memory_order_relaxed))
    return props;

  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();
  key_endpoint keylist;

    keylist.add_key_endpoint(std::list<uint32_t>{0});
  props.m_members_by_seq.push_back(get_type_props<int32_t>());  //::userID
  props.m_members_by_seq.back().set_member_props(0,false);
  props.m_members_by_seq.push_back(get_type_props<char>());  //::message
  props.m_members_by_seq.back().set_member_props(1,false);
  props.m_members_by_seq.back().e_bb = bb_unset;

  props.m_members_by_seq.push_back(final_entry());

  props.finish(keylist);
  initialized.store(true, std::memory_order::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

