/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: apa_nav.c
  Source: apa_nav.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "apa_nav.h"

static const uint32_t byd_interfaces_msg_apa_nav_ops [] =
{
  /* apa_nav */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_apa_nav, TimeStampMs),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_apa_nav, nav_pos_x),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_apa_nav, nav_pos_y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_apa_nav, nav_heading),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_apa_nav, nav_status),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_apa_nav_desc =
{
  .m_size = sizeof (byd_interfaces_msg_apa_nav),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::apa_nav_",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = byd_interfaces_msg_apa_nav_ops,
  .m_meta = ""
};

