/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_status.c
  Source: app_status.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "app_status.h"

static const uint32_t byd_interfaces_msg_app_status_ops [] =
{
  /* app_status */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_status, APAStatus),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_app_status_desc =
{
  .m_size = sizeof (byd_interfaces_msg_app_status),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::app_status_",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = byd_interfaces_msg_app_status_ops,
  .m_meta = ""
};

