/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_park.c
  Source: app_park.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "app_park.h"

static const uint32_t byd_interfaces_msg_app_park_ops [] =
{
  /* app_park */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_app_park, selectedInfo), (3u << 16u) + 4u /* SelectedInfo */,
  DDS_OP_RTS,

  /* SelectedInfo */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_SelectedInfo, SelectID),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_SelectedInfo, Width),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_SelectedInfo, ParkingSpaceValid),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_SelectedInfo, ParkingSpaceAvailable),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (apa_msgs_msg_SelectedInfo, ParkingSpaceType),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_app_park_desc =
{
  .m_size = sizeof (byd_interfaces_msg_app_park),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::app_park_",
  .m_keys = NULL,
  .m_nops = 16,
  .m_ops = byd_interfaces_msg_app_park_ops,
  .m_meta = ""
};

