/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_ui_action.c
  Source: app_ui_action.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "app_ui_action.h"

static const uint32_t byd_interfaces_msg_app_ui_action_ops [] =
{
  /* app_ui_action */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_ui_action, APA_Function_Selected_Area),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_ui_action, APA_Function_Tips_Area),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_ui_action, APA_Function_UI_Area),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_ui_action, APA_Function_ButtonSelected_Area),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_ui_action, AVM_APA_Selected),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_app_ui_action_desc =
{
  .m_size = sizeof (byd_interfaces_msg_app_ui_action),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::app_ui_action_",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = byd_interfaces_msg_app_ui_action_ops,
  .m_meta = ""
};

