/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_ui_nextstep.c
  Source: app_ui_nextstep.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "app_ui_nextstep.h"

static const uint32_t byd_interfaces_msg_app_ui_nextstep_ops [] =
{
  /* app_ui_nextstep */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_app_ui_nextstep, parking_next_nextstep), (3u << 16u) + 4u /* Parking_next_nextstep */,
  DDS_OP_RTS,

  /* Parking_next_nextstep */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Parking_next_nextstep, P3_Y),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_app_ui_nextstep_desc =
{
  .m_size = sizeof (byd_interfaces_msg_app_ui_nextstep),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::app_ui_nextstep_",
  .m_keys = NULL,
  .m_nops = 11,
  .m_ops = byd_interfaces_msg_app_ui_nextstep_ops,
  .m_meta = ""
};

