/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: app_mode.c
  Source: app_mode.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "app_mode.h"

static const uint32_t byd_interfaces_msg_app_mode_ops [] =
{
  /* app_mode */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_app_mode, ParkInMode),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_app_mode_desc =
{
  .m_size = sizeof (byd_interfaces_msg_app_mode),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::app_mode_",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = byd_interfaces_msg_app_mode_ops,
  .m_meta = ""
};

