/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: BYDAutoInterface.c
  Source: BYDAutoInterface.idltmp
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "BYDAutoInterface.h"

static const uint32_t byd_interfaces_msg_BYDAutoInterface_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_BYDAutoInterface, value_type),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_BYDAutoInterface, feature_id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_BYDAutoInterface, int32_value),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (byd_interfaces_msg_BYDAutoInterface, float32_value),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_BYDAutoInterface, char_value_array), 46u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_BYDAutoInterface, value_size),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_BYDAutoInterface_desc =
{
  sizeof (byd_interfaces_msg_BYDAutoInterface),
  4u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "byd_interfaces::msg::dds_::BYDAutoInterface_",
  NULL,
  7,
  byd_interfaces_msg_BYDAutoInterface_ops,
  ""
};
