#include "nav_msgs/msg/Position.idl"
#include "nav_msgs/msg/Freespacecell.idl"
#include "nav_msgs/msg/Parkingspaceinfo.idl"
#include "nav_msgs/msg/ObstacleInfo.idl"


#ifndef __byd_interfaces__msg__cam__sensing__idl__
#define  __byd_interfaces__msg__cam__sensing__idl__

module byd_interfaces {
  module msg {
    struct cam_sensing {
      long long TimeStampMs;
      uss_msgs::msg::Position position;
       uss_msgs::msg::ParkingSpaceInfo parkingSpaceInfo[25];
       uss_msgs::msg:: FreeSpaceCell freeSpaceCell[62500];
     uss_msgs::msg:: ObstacleInfo ObstacleInfo[25];
   };
  };
};
#endif
