#include "nav_msgs/msg/Position.idl"
#include "nav_msgs/msg/Freespacecell.idl"
#include "nav_msgs/msg/Parkingspaceinfo.idl"
#include "nav_msgs/msg/ObstacleInfo.idl"


#ifndef __byd_interfaces__msg__cam__ai__obstale__idl__
#define  __byd_interfaces__msg__cam__ai__obstale__idl__

module byd_interfaces {
  module msg {
    struct cam_ai_obstacle {
      long long TimeStampMs;
      uss_msgs::msg::Position position;
       uss_msgs::msg:: ObstacleInfo ObstacleInfo[25];
   };
  };
};
#endif
