/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Coordinate.c
  Source: Coordinate.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Coordinate.h"

static const uint32_t uss_msgs_msg_Coordinate_ops [] =
{
  /* Coordinate */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, Yaw),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_Coordinate, rajectoryDirection),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, Curvature),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_Coordinate_desc =
{
  .m_size = sizeof (uss_msgs_msg_Coordinate),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::Coordinate_",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = uss_msgs_msg_Coordinate_ops,
  .m_meta = ""
};

