#ifndef __byd_interfaces__msg__Freespacefusion__idl__
#define __byd_interfaces__msg__Freespacefusion__idl__

module uss_msgs {
  module msg {
    struct FreeSpacefusion {
   uint8 Status;
};
  };
};
#endif
