#ifndef __byd_interfaces__msg__Freespacecell__rt__idl__
#define __byd_interfaces__msg__Freespacecell__rt__idl__

module uss_msgs {
  module msg {
    struct FreeSpaceCell_RT{
   uint8 Status;
   uint16 Probability;

};
  };
};
#endif
