#include "std_msgs/msg/Header.idl"
#include "nav_msgs/msg/Parkingspaceinfo.idl"
#include "nav_msgs/msg/Position.idl"
#include "nav_msgs/msg/Freespacecell.idl"
#include "nav_msgs/msg/ObstacleInfo2.idl"
#include "nav_msgs/msg/head.idl"


#ifndef __byd_interfaces__msg__fusion__parkinginfo__idl__
#define __byd_interfaces__msg__fusion__parkinginfo__idl__

module byd_interfaces {
  module msg {
    struct fusion_parkinginfo {
      long long TimeStampMs;
      uss_msgs::msg::Position position;
      uss_msgs::msg::ParkingSpaceInfo parkingSpaceInfo[25];
      uint8 TraceParkingID_Cam;
	    uint8 TraceParkingID_USS;
	    double Theta;
     uint8 ParkInMode; 
    };
  };
};
#endif
