/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: fusion_gridmap.c
  Source: fusion_gridmap.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "fusion_gridmap.h"

static const uint32_t byd_interfaces_msg_fusion_gridmap_ops [] =
{
  /* fusion_gridmap */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_fusion_gridmap, TimeStampMs),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_fusion_gridmap, position), (3u << 16u) + 9u /* Position */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (byd_interfaces_msg_fusion_gridmap, freeSpacefusion), 62500u, (5u << 16u) + 13u /* FreeSpacefusion */, sizeof (uss_msgs_msg_FreeSpacefusion),
  DDS_OP_RTS,

  /* Position */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Heading),
  DDS_OP_RTS,

  /* FreeSpacefusion */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_FreeSpacefusion, Status),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_fusion_gridmap_desc =
{
  .m_size = sizeof (byd_interfaces_msg_fusion_gridmap),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::fusion_gridmap_",
  .m_keys = NULL,
  .m_nops = 10,
  .m_ops = byd_interfaces_msg_fusion_gridmap_ops,
  .m_meta = ""
};

