/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: head.c
  Source: head.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "head.h"

static const uint32_t uss_msgs_msg_Head_ops [] =
{
  /* Head */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Head, x),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_Head, y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Head, Heading),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_Head_desc =
{
  .m_size = sizeof (uss_msgs_msg_Head),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::Head_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = uss_msgs_msg_Head_ops,
  .m_meta = ""
};

