/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: hmi_ui_app.c
  Source: hmi_ui_app.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "hmi_ui_app.h"

static const uint32_t byd_interfaces_msg_hmi_ui_app_ops [] =
{
  /* hmi_ui_app */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_hmi_ui_app, seletedParking), (3u << 16u) + 10u /* SeletedParking */,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_hmi_ui_app, ButtonType),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_hmi_ui_app, SelectParkingMode),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_hmi_ui_app, ParkInMode),
  DDS_OP_RTS,

  /* SeletedParking */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_SeletedParking, ParkingNum),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_SeletedParking, Width),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_SeletedParking, ParkingSpaceValid),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_SeletedParking, ParkingSpaceAvailable),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_SeletedParking, ParkingSpaceType),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_hmi_ui_app_desc =
{
  .m_size = sizeof (byd_interfaces_msg_hmi_ui_app),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::hmi_ui_app_",
  .m_keys = NULL,
  .m_nops = 19,
  .m_ops = byd_interfaces_msg_hmi_ui_app_ops,
  .m_meta = ""
};

