#include "nav_msgs/msg/seletedParking.idl"

#ifndef __byd_interfaces__msg__hmi__ui__app__idl__
#define __byd_interfaces__msg__hmi__ui__app__idl__

module byd_interfaces {
  module msg {
    struct hmi_ui_app {
      uss_msgs::msg::SeletedParking seletedParking;
      uint8 ButtonType;
      uint8 SelectParkingMode;
      uint8 ParkInMode; 
    };
  };
};
#endif
