#ifndef __byd_interfaces__msg__ObstacleInfo2__idl__
#define __byd_interfaces__msg__ObstacleInfo2__idl__

module uss_msgs {
  module msg {
    struct ObstacleInfo2 {
   uint8 ObstacleType;
    int32 Obstacle_X;
    int32 Obstacle_Y;
};
  };
};
#endif
