/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: ObstacleInfo.c
  Source: ObstacleInfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "ObstacleInfo.h"

static const uint32_t uss_msgs_msg_ObstacleInfo_ops [] =
{
  /* ObstacleInfo */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ObstacleInfo, ObstacleType),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ObstacleInfo, Obstacle_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (uss_msgs_msg_ObstacleInfo, Obstacle_Y),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ObstacleInfo, VehicleDirection),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_ObstacleInfo_desc =
{
  .m_size = sizeof (uss_msgs_msg_ObstacleInfo),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::ObstacleInfo_",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = uss_msgs_msg_ObstacleInfo_ops,
  .m_meta = ""
};

