#ifndef __byd_interfaces__msg__Parkingspaceinfo2__idl__
#define __byd_interfaces__msg__Parkingspaceinfo2__idl__

module uss_msgs {
  module msg {
    struct ParkingSpaceInfo2 {
         uint8 id;
          uint32 P0_X;
          uint32 P0_Y;
          uint32 P1_X;
          uint32 P1_Y;
          uint32 P2_X;
          uint32 P2_Y;
          uint32 P3_X;
          uint32 P3_Y;
         uint32 Width;
          uint8 ParkingSpaceValid;
          uint8 ParkingSpaceType;
    
    };
  };
};
#endif
