/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Parkingspaceinfo2.c
  Source: Parkingspaceinfo2.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Parkingspaceinfo2.h"

static const uint32_t uss_msgs_msg_ParkingSpaceInfo2_ops [] =
{
  /* ParkingSpaceInfo2 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, Width),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, ParkingSpaceValid),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_ParkingSpaceInfo2, ParkingSpaceType),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_ParkingSpaceInfo2_desc =
{
  .m_size = sizeof (uss_msgs_msg_ParkingSpaceInfo2),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::ParkingSpaceInfo2_",
  .m_keys = NULL,
  .m_nops = 13,
  .m_ops = uss_msgs_msg_ParkingSpaceInfo2_ops,
  .m_meta = ""
};

