/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: plan_pathinfo_ctrl.c
  Source: plan_pathinfo_ctrl.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "plan_pathinfo_ctrl.h"

static const uint32_t byd_interfaces_msg_plan_pathinfo_ctrl_ops [] =
{
  /* plan_pathinfo_ctrl */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_plan_pathinfo_ctrl, TimeStampMs),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_plan_pathinfo_ctrl, TrajectoryLength),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (byd_interfaces_msg_plan_pathinfo_ctrl, coordinate), 300u, (5u << 16u) + 6u /* Coordinate */, sizeof (uss_msgs_msg_Coordinate),
  DDS_OP_RTS,

  /* Coordinate */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, Yaw),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_Coordinate, rajectoryDirection),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Coordinate, Curvature),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_plan_pathinfo_ctrl_desc =
{
  .m_size = sizeof (byd_interfaces_msg_plan_pathinfo_ctrl),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::plan_pathinfo_ctrl_",
  .m_keys = NULL,
  .m_nops = 10,
  .m_ops = byd_interfaces_msg_plan_pathinfo_ctrl_ops,
  .m_meta = ""
};

