/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RadarDataUPA.c
  Source: RadarDataUPA.idltmp
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "RadarDataUPA.h"

static const uint32_t byd_interfaces_msg_RadarDataUPA_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_RadarDataUPA, time.stamp.sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_RadarDataUPA, time.stamp.nanosec),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (byd_interfaces_msg_RadarDataUPA, time.frame_id),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_RadarDataUPA, chl),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (byd_interfaces_msg_RadarDataUPA, distance),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_RadarDataUPA_desc =
{
  sizeof (byd_interfaces_msg_RadarDataUPA),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "byd_interfaces::msg::dds_::RadarDataUPA_",
  NULL,
  6,
  byd_interfaces_msg_RadarDataUPA_ops,
  ""
};
