/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RadarDataAPA.c
  Source: RadarDataAPA.idltmp
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "RadarDataAPA.h"

static const uint32_t byd_interfaces_msg_RadarDataAPA_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_RadarDataAPA, time.stamp.sec),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_RadarDataAPA, time.stamp.nanosec),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (byd_interfaces_msg_RadarDataAPA, time.frame_id),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_RadarDataAPA, chl),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (byd_interfaces_msg_RadarDataAPA, status),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_RadarDataAPA, num),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY, offsetof (byd_interfaces_msg_RadarDataAPA, ts), 16u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_RadarDataAPA_desc =
{
  sizeof (byd_interfaces_msg_RadarDataAPA),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "byd_interfaces::msg::dds_::RadarDataAPA_",
  NULL,
  8,
  byd_interfaces_msg_RadarDataAPA_ops,
  ""
};
