#ifndef __byd_interfaces__msg__seletedParking__idl__
#define __byd_interfaces__msg__seletedParking__idl__

module uss_msgs {
  module msg {
    struct SeletedParking {
   uint8 ParkingNum;
	int32 P0_X;
	int32 P0_Y;
	int32 P1_X;
	int32 P1_Y;
	int32 P2_X;
	int32 P2_Y;
	int32 P3_X;
	int32 P3_Y;
	int32 Width;
	uint8 ParkingSpaceValid;
	uint8 ParkingSpaceAvailable;
	uint8 ParkingSpaceType;
};
  };
};
#endif
