#ifndef __byd_interfaces__msg__Selectedinfo__idl__
#define __byd_interfaces__msg__Selectedinfo__idl__

module apa_msgs {
  module msg {
    struct SelectedInfo {
    uint8 SelectID;
    int32 P0_X;
    int32 P0_Y;
    int32 P1_X;
    int32 P1_Y;
    int32 P2_X;
    int32 P2_Y;
    int32 P3_X;
    int32 P3_Y;
    int32 Width;
    uint8 ParkingSpaceValid;
    uint8 ParkingSpaceAvailable;
    uint8 ParkingSpaceType;
};
  };
};
#endif
