/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: ShmData.c
  Source: ShmData.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "ShmData.h"

static const uint32_t byd_interfaces_msg_ShmData_Base_ops [] =
{
  /* ShmData_Base */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_Base, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_Base, payloadsize),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_Base_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_Base),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_Base_",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = byd_interfaces_msg_ShmData_Base_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_16_ops [] =
{
  /* ShmData_16 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_16, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_16, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_16, payload), 4u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_16_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_16),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_16_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_16_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_32_ops [] =
{
  /* ShmData_32 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_32, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_32, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_32, payload), 20u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_32_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_32),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_32_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_32_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_64_ops [] =
{
  /* ShmData_64 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_64, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_64, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_64, payload), 52u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_64_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_64),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_64_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_64_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_128_ops [] =
{
  /* ShmData_128 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_128, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_128, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_128, payload), 116u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_128_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_128),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_128_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_128_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_256_ops [] =
{
  /* ShmData_256 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_256, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_256, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_256, payload), 244u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_256_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_256),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_256_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_256_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_512_ops [] =
{
  /* ShmData_512 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_512, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_512, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_512, payload), 500u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_512_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_512),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_512_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_512_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_1024_ops [] =
{
  /* ShmData_1024 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_1024, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_1024, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_1024, payload), 1012u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_1024_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_1024),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_1024_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_1024_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_2048_ops [] =
{
  /* ShmData_2048 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_2048, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_2048, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_2048, payload), 2036u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_2048_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_2048),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_2048_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_2048_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_4096_ops [] =
{
  /* ShmData_4096 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_4096, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_4096, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_4096, payload), 4084u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_4096_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_4096),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_4096_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_4096_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_8192_ops [] =
{
  /* ShmData_8192 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_8192, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_8192, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_8192, payload), 8180u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_8192_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_8192),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_8192_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_8192_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_16384_ops [] =
{
  /* ShmData_16384 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_16384, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_16384, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_16384, payload), 16372u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_16384_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_16384),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_16384_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_16384_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_32768_ops [] =
{
  /* ShmData_32768 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_32768, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_32768, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_32768, payload), 32756u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_32768_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_32768),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_32768_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_32768_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_65536_ops [] =
{
  /* ShmData_65536 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_65536, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_65536, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_65536, payload), 65524u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_65536_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_65536),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_65536_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_65536_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_131072_ops [] =
{
  /* ShmData_131072 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_131072, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_131072, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_131072, payload), 131060u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_131072_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_131072),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_131072_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_131072_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_262144_ops [] =
{
  /* ShmData_262144 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_262144, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_262144, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_262144, payload), 262132u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_262144_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_262144),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_262144_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_262144_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_524288_ops [] =
{
  /* ShmData_524288 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_524288, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_524288, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_524288, payload), 524276u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_524288_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_524288),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_524288_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_524288_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_1048576_ops [] =
{
  /* ShmData_1048576 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_1048576, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_1048576, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_1048576, payload), 1048564u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_1048576_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_1048576),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_1048576_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_1048576_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_2097152_ops [] =
{
  /* ShmData_2097152 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_2097152, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_2097152, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_2097152, payload), 2097140u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_2097152_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_2097152),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_2097152_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_2097152_ops,
  .m_meta = ""
};

static const uint32_t byd_interfaces_msg_ShmData_4194304_ops [] =
{
  /* ShmData_4194304 */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_ShmData_4194304, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_ShmData_4194304, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (byd_interfaces_msg_ShmData_4194304, payload), 4194292u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_ShmData_4194304_desc =
{
  .m_size = sizeof (byd_interfaces_msg_ShmData_4194304),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::ShmData_4194304_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_ShmData_4194304_ops,
  .m_meta = ""
};

