/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: UdpTestData.c
  Source: UdpTestData.idltmp
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "UdpTestData.h"

static const uint32_t byd_interfaces_msg_UdpTestData_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_UdpTestData, seq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_UdpTestData, count),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (byd_interfaces_msg_UdpTestData, payloadsize),
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (byd_interfaces_msg_UdpTestData, delay),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (byd_interfaces_msg_UdpTestData, data),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_UdpTestData_desc =
{
  sizeof (byd_interfaces_msg_UdpTestData),
  8u,
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "byd_interfaces::msg::dds_::UdpTestData_",
  NULL,
  6,
  byd_interfaces_msg_UdpTestData_ops,
  ""
};
