/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Uss_ui.c
  Source: Uss_ui.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Uss_ui.h"

static const uint32_t uss_msgs_msg_Uss_UI_ops [] =
{
  /* Uss_UI */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (uss_msgs_msg_Uss_UI, timestamp),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Uss_UI, distance_app), 12u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_Uss_UI_desc =
{
  .m_size = sizeof (uss_msgs_msg_Uss_UI),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::Uss_UI_",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = uss_msgs_msg_Uss_UI_ops,
  .m_meta = ""
};

