/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: uss_map.c
  Source: uss_map.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "uss_map.h"

static const uint32_t byd_interfaces_msg_uss_map_ops [] =
{
  /* uss_map */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (byd_interfaces_msg_uss_map, TimeStampMs),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (byd_interfaces_msg_uss_map, position), (3u << 16u) + 9u /* Position */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (byd_interfaces_msg_uss_map, freeSpaceCell), 62500u, (5u << 16u) + 13u /* FreeSpaceCell */, sizeof (uss_msgs_msg_FreeSpaceCell),
  DDS_OP_RTS,

  /* Position */
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, X),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Y),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_Position, Heading),
  DDS_OP_RTS,

  /* FreeSpaceCell */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (uss_msgs_msg_FreeSpaceCell, Status),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (uss_msgs_msg_FreeSpaceCell, Probability),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_uss_map_desc =
{
  .m_size = sizeof (byd_interfaces_msg_uss_map),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::uss_map_",
  .m_keys = NULL,
  .m_nops = 11,
  .m_ops = byd_interfaces_msg_uss_map_ops,
  .m_meta = ""
};

