#ifndef __byd_interfaces__msg__Ussinfo__app__idl__
#define __byd_interfaces__msg__Ussinfo__app__idl__

module uss_msgs {
  module msg {
    struct UssInfo_app {
  uint64 timestamp;
	double distance_app;  
  double theta_app;
};
  };
};
#endif
