/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Ussinfo_app.c
  Source: Ussinfo_app.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Ussinfo_app.h"

static const uint32_t uss_msgs_msg_UssInfo_app_ops [] =
{
  /* UssInfo_app */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (uss_msgs_msg_UssInfo_app, timestamp),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_UssInfo_app, distance_app),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (uss_msgs_msg_UssInfo_app, theta_app),
  DDS_OP_RTS
};

const dds_topic_descriptor_t uss_msgs_msg_UssInfo_app_desc =
{
  .m_size = sizeof (uss_msgs_msg_UssInfo_app),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "uss_msgs::msg::dds_::UssInfo_app_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = uss_msgs_msg_UssInfo_app_ops,
  .m_meta = ""
};

