/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: vehiclecontrol_app_parkinginfo.c
  Source: vehiclecontrol_app_parkinginfo.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "vehiclecontrol_app_parkinginfo.h"

static const uint32_t byd_interfaces_msg_vehiclecontrol_app_parkinginfo_ops [] =
{
  /* vehiclecontrol_app_parkinginfo */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_vehiclecontrol_app_parkinginfo, Completed_App),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_vehiclecontrol_app_parkinginfo, ObstacleOnPath),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (byd_interfaces_msg_vehiclecontrol_app_parkinginfo, PlanOvertime),
  DDS_OP_RTS
};

const dds_topic_descriptor_t byd_interfaces_msg_vehiclecontrol_app_parkinginfo_desc =
{
  .m_size = sizeof (byd_interfaces_msg_vehiclecontrol_app_parkinginfo),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "byd_interfaces::msg::dds_::vehiclecontrol_app_parkinginfo_",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = byd_interfaces_msg_vehiclecontrol_app_parkinginfo_ops,
  .m_meta = ""
};

