#ifndef __byd_interfaces__msg__vehiclecontrol__planj__interfaceinfo__idl__
#define __byd_interfaces__msg__vehiclecontrol__planj__interfaceinfo__idl__

module byd_interfaces {
  module msg {
    struct vehiclecontrol_planj_interfaceinfo{
    uint8 PlanningRequestCount;
    };
  };
};
#endif
