/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  The generate program idlc named byd_idl has been modified by BYD
  File name: Vehtarposndisp.c
  Source: Vehtarposndisp.idl
  Cyclone DDS: V0.9.1

*****************************************************************/
#include "Vehtarposndisp.h"

static const uint32_t apa_msgs_msg_VehTarPosnDisp_ops [] =
{
  /* VehTarPosnDisp */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P0_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P0_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P1_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P1_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P2_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P2_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P3_X),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, P3_Y),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (apa_msgs_msg_VehTarPosnDisp, Width),
  DDS_OP_RTS
};

const dds_topic_descriptor_t apa_msgs_msg_VehTarPosnDisp_desc =
{
  .m_size = sizeof (apa_msgs_msg_VehTarPosnDisp),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "apa_msgs::msg::dds_::VehTarPosnDisp_",
  .m_keys = NULL,
  .m_nops = 10,
  .m_ops = apa_msgs_msg_VehTarPosnDisp_ops,
  .m_meta = ""
};

